apiVersion: v1
kind: Service
metadata:
  name: {{ template "jobmanager.fullname" . }}-builder
  labels:
{{ include "jobmanager.labels" (dict "root" . "service" "builder") | indent 4}}
spec:
  selector:
{{ include "jobmanager.selectors" (dict "root" . "service" "builder") | indent 4}}
  type: NodePort
  ports:
  - name: "5001-5001"
    port: 5001
    targetPort: 5001
status:
  loadBalancer: {}
