apiVersion: v1
kind: Service
metadata:
  name: {{ template "jobmanager.fullname" . }}-api
  labels:
{{ include "jobmanager.labels" (dict "root" . "service" "api") | indent 4}}
spec:
  type: NodePort
  selector:
{{ include "jobmanager.selectors" (dict "root" . "service" "api") | indent 4}}
  ports:
  - name: "5000-5000"
    port: 5000
    targetPort: 5000
status:
  loadBalancer: {}
