apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "jobmanager.fullname" . }}-mongodb
  labels:
{{ include "jobmanager.labels" (dict "root" . "service" "mongodb") | indent 4}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "jobmanager.selectors" (dict "root" . "service" "mongodb") | indent 6}}
  template:
    metadata:
      labels:
{{ include "jobmanager.selectors" (dict "root" . "service" "mongodb") | indent 8}}
    spec:
      restartPolicy: Always
      containers:
      - image: {{ template "jobmanager.image" .Values.mongodb }}
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy | quote }}
        name: {{ template "jobmanager.fullname" . }}-mongodb
        ports:
        - containerPort: 27017
#        args:
#        - mongod
#        - --smallfiles
#        - --bind_ip="0.0.0.0"
#        - --dbpath=/data/db/
#        - --logpath=/data/mongod.txt
        env:
        - name: MONGO_DATA_DIR
          value: "/data/db/"
        - name: MONGO_LOG_DIR
          value: "/data/"
#        - name: MONGODB_ENABLE_IPV6
#          value: "no"
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: {{ template "jobmanager.fullname" . }}-mongodb-claim0
      volumes:
      - name: {{ template "jobmanager.fullname" . }}-mongodb-claim0
        persistentVolumeClaim:
          claimName: {{ template "jobmanager.fullname" . }}-mongodb-claim0
status: {}
