{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "jobmanager.fullname" . }}-mongodb-claim0
  labels:
{{ include "jobmanager.labels" (dict "root" . "service" "mongodb") | indent 4}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage | quote }}
status: {}

{{- end -}}