apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "jobmanager.fullname" . }}-registry-claim0
  labels:
{{ include "jobmanager.labels" (dict "root" . "service" "registry") | indent 4}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.registry.storage }}
status: {}
