version: '2'
services:
    jobmanager-api:
        image: jobmanager-api:latest
        environment:
            - JOBMANAGER_DATABASE_HOST=mongodb
            - JOBMANAGER_API_HTTP_PORT=5000
            - JOBMANAGER_API_IMPORTS=jobmanager.common.example
            - JOBMANAGER_API_VERBOSITY=DEBUG
            - JOBMANAGER_API_DEBUG=true
            - APP_NAME=CineCoder
        ports:
            - 5000:5000
        links:
            - mongodb
        depends_on:
            - mongodb
    jobmanager-client:
        image: jobmanager-client-coder:latest
        environment:
            - JOBMANAGER_DATABASE_HOST=mongodb
            - JOBMANAGER_CLIENT_IMPORTS=jobmanager.common.example
            - JOBMANAGER_CLIENT_VERBOSITY=DEBUG
            - JOBMANAGER_CLIENT_DEBUG=true
        links:
            - mongodb
            - jobmanager_api
        depends_on:
            - mongodb
    jobmanager-builder:
        image: jobmanager-builder:latest
        environment:
            - JOBMANAGER_DATABASE_HOST=mongodb
            - JOBMANAGER_BUILDER_HTTP_PORT=5001
            - JOBMANAGER_DOCKER_REGISTRY_URL=registry:5000
            - JOBMANAGER_BUILDER_VERBOSITY=DEBUG
            - JOBMANAGER_BUILDER_DEBUG=true
        ports:
            - 5001:5001
        links:
            - mongodb
            - registry
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - mongodb
            - registry
    registry:
        image: registry:2
        restart: always
        # environment:
        #   REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
        #   REGISTRY_HTTP_TLS_KEY: /certs/domain.key
        #   REGISTRY_AUTH: htpasswd
        #   REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        #   REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
          - ./data/registry:/var/lib/registry
          # - /path/certs:/certs
          # - /path/auth:/auth
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/opt/mongodb/data
          - MONGO_LOG_DIR=/opt/mongodb/logs
        volumes:
          - ./data/db:/opt/mongodb/data
          - ./data/logs:/opt/mongodb/logs
        ports:
            - 27018:27017
        command: mongod --smallfiles --logpath=/opt/mongodb/logs/mongod.txt # --quiet